- name: allow remote operations
  command: "{{ lxd_lxc_path }} config set core.https_address {{ lxd_https_listen_address }}"
  when: lxd_allow_remote

- name: set password for remote operations
  command: "{{ lxd_lxc_path }} config set core.trust_password '{{ lxd_trust_password }}'"
  when: lxd_allow_remote
